name: Build + Release
on:
  push:
    branches:
      - "**"
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xom9ikk/dotenv@v2
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          log-accepted-android-sdk-licenses: false
          packages: ''
      - run: sdkmanager --install "ndk;$FFMPEG_ANDROID_NDK_VERSION"
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: find dist/ -printf "%P\n" | tar -czf release.tar.gz --no-recursion -C dist/ -T -
      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.tar.gz
  release:
    runs-on: ubuntu-latest
    needs: build
    if: success() && startsWith( github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - uses: ncipollo/release-action@v1
        with:
          artifacts: release.tar.gz
